---
- name: install apache
  become: true
  yum:
    name: "httpd"
    state: present

- name: set directory root to index.php
  become: yes
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^DirectoryIndex index.html'
    line: DirectoryIndex index.php     
    insertafter: <IfModule dir_module>

- name: install git
  become: yes
  yum:
    name: "git"
    state: present

- name: clone a repo
  become: yes
  git:
    repo: https://github.com/ojoimmanuel/tooling.git
    dest: /var/www/html
    force: yes

- name: copy html content to one level up
  become: true
  command: cp -r /var/www/html/html/ /var/www/

- name: Start service httpd, if not started
  become: yes
  service:
    name: httpd
    state: started

- name: recursively remove /var/www/html/html/ directory
  become: yes
  file:
    path: /var/www/html/html
    state: absent